export const Core = [
    {
        'fullName': 'Rishabh Sharma',
        'username': 'Rishabh',
        'rollNumber': 'na20b051',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com/in/rishabh-sharma-a35440202',
        'email': 'goldenrishabh@smail.iitm.ac.in',
    },
    {
        'fullName': 'Bindusara Reddy',
        'username': 'Bindusara',
        'rollNumber': 'Na20b013',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com/in/bindusara-reddy-890b131b9/',
        'email': 'na20b013@smail.iitm.ac.in',
    },
    {
        'fullName': 'Aditya Ravindran',
        'username': 'Aditya',
        'rollNumber': 'NA20B004',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com/in/aditya-ravindran-1b734b211/',
        'email': 'na20b004@smail.iitm.ac.in',
    },
    {
        'fullName': 'Raaed Shajihan',
        'username': 'Raaed',
        'rollNumber': 'me20b141',
        'subModule': 'Chassis',
        'linkedIn': 'https://www.linkedin.com/in/raaed-shajihan',
        'email': 'me20b141@smail.iitm.ac.in',
    },
    {
        'fullName': 'Anirudh Varna',
        'username': 'Anirudh',
        'rollNumber': 'NA20B007',
        'subModule': 'Low voltage',
        'linkedIn': 'https://www.linkedin.com/in/anirudh-varna-b5b0451b9',
        'email': 'anirudhrubix@gmail.com',
    },
]

export const Mech = [
    {
        'fullName': 'Ananth Kulkarni',
        'username': 'Ananth',
        'rollNumber': 'ME21B020',
        'subModule': 'Vehicle dynamics',
        'linkedIn': 'https://www.linkedin.com/in/ananthkulkarni23',
        'email': 'me21b020@smail.iitm.ac.in',
    },
    {
        'fullName': 'Sanjay Keyan',
        'username': 'Sanjay',
        'rollNumber': 'NA21B062',
        'subModule': 'Chassis',
        'linkedIn': 'https://www.linkedin.com/in/sanjaykeyan/',
        'email': 'na21b062@smail.iitm.ac.in',
    },
    {
        'fullName': 'Pragyandipta Mishra',
        'username': 'Pragyandipta',
        'rollNumber': 'AM19D751',
        'subModule': 'Vehicle dynamics',
        'linkedIn': 'https://www.linkedin.com/in/pragyandipta-mishra/',
        'email': 'pragyandipta@smail.iitm.ac.in',
    },
    {
        'fullName': 'Sreesudhan',
        'username': 'Sreesudhan',
        'rollNumber': 'AE21B057',
        'subModule': 'Aerodynamics',
        'linkedIn': 'https://www.linkedin.com/in/sreesudhan-b-1a0a84237/',
        'email': 'ae21b057@smail.iitm.ac.in',
    },
    {
        'fullName': 'Pradyum kaneria',
        'username': 'Pradyum',
        'rollNumber': 'ME21B142',
        'subModule': 'Aerodynamics',
        'linkedIn': 'https://www.linkedin.com/in/pradyum-kaneria-7a89a925b',
        'email': 'Me21b142@smail.iitm.ac.in',
    },
    {
        'fullName': 'Pranav Mantripragada ',
        'username': 'Pranav',
        'rollNumber': 'ME21B203',
        'subModule': 'Chassis',
        'linkedIn': 'https://www.linkedin.com/in/pranav-mantripragada-1995b6249',
        'email': 'me21b203@smail.iitm.ac.in ',
    },
    {
        'fullName': 'Dhruv Bawa ',
        'username': 'Dhruv',
        'rollNumber': 'ME20B061 ',
        'subModule': 'Chassis',
        'linkedIn': 'https://www.linkedin.com/in/dhruv-bawa-896409238',
        'email': 'me20b061@smail.iitm.ac.in',
    },
    {
        'fullName': 'Akash Thakur',
        'username': 'Akash',
        'rollNumber': 'AE21B102',
        'subModule': 'Aerodynamics',
        'linkedIn': 'https://www.linkedin.com/in/akash-thakur-6696a6239',
        'email': 'ae21b102@smail.iitm.ac.in',
    },
    {
        'fullName': 'Kartik Ruikar',
        'username': 'Kartik',
        'rollNumber': 'NA20B053',
        'subModule': 'Aerodynamics',
        'linkedIn': 'https://www.linkedin.com/in/kartik-ruikar-2605',
        'email': 'na20b053@smail.iitm.ac.in ',
    },
]

export const Elec = [
    {
        'fullName': 'Jaayanth Srrinivas Kumaran ',
        'username': 'Jaayanth',
        'rollNumber': 'ED21B029',
        'subModule': 'Low voltage',
        'linkedIn': 'https://www.linkedin.com/in/jaayanth-sk',
        'email': 'jaayanth.jr@gmail.com',
    },
    {
        'fullName': 'Kunjeti Dharanidhar Gupta',
        'username': 'Dharanidhar',
        'rollNumber': 'EP21B022',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com/in/dharanidhar-kunjeti-40a1bb226',
        'email': 'ep21b022@smail.iitm.ac.in',
    },
    {
        'fullName': 'Ram Parameswar Menon',
        'username': 'Ram',
        'rollNumber': 'CE21B104',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com/in/ram-parameswar-menon-b81318224',
        'email': 'ramparameswarmenon@gmail.com',
    },
    {
        'fullName': 'Parveet Kumar',
        'username': 'Parveet',
        'rollNumber': 'EE21B099',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com/in/parveet-kumar-ab9792232',
        'email': 'kumarparveet14@gmail.com',
    },
    {
        'fullName': 'Pushpa Chaudhary',
        'username': 'Pushpa',
        'rollNumber': 'EE21B109',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com/in/pushpa-chaudhary-9b5914225/',
        'email': 'ee21b109@smail.iitm.ac.in',
    },
    {
        'fullName': 'Keshaw Choudhary ',
        'username': 'Keshaw',
        'rollNumber': '',
        'subModule': 'High voltage',
        'linkedIn': '',
        'email': 'keshawchoudhary152@gmail.com',
    },
    {
        'fullName': 'Fardeen',
        'username': 'Fardeen',
        'rollNumber': 'EE21B046',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com/in/fardeen-razif',
        'email': 'ee21b046@smail.iitm.ac.in',
    },

]

export const Spons = [
    {
        'fullName': 'Chirag Meher',
        'username': 'Chirag',
        'rollNumber': 'NA21B019',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com/in/chiragmeher',
        'email': 'meher.chirag20@gmail.com',
    },
    {
        'fullName': 'Damyanti Jain',
        'username': 'Damyanti',
        'rollNumber': 'NA21B020',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com/in/damyanti-jain-372688224/',
        'email': 'damyantijain17@gmail.com',
    },
    {
        'fullName': 'Sujith Kumar ',
        'username': 'Sujith',
        'rollNumber': 'NA20B067 ',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com/in/sujith-kumar-a10809217/',
        'email': 'na20b067@smail.iitm.ac.in',
    },
    {
        'fullName': 'PRABHAT UDDARAJU ',
        'username': 'Prabhat',
        'rollNumber': 'AE21B012',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com/in/uddaraju-chandra-prabhat-varma-285452235',
        'email': 'prabhatuddaraju@gmail.com',
    },
    {
        'fullName': 'Sagar Nagapnor',
        'username': 'Sagar',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedIn.com/in/SagarNagapnor',
        'email': 'ed20b054@smail.iitm.ac.in',
    },
    // {
    //     'fullName': '',
    //     'username': '',
    //     'rollNumber': '',
    //     'subModule': 'NA',
    //     'linkedIn': '',
    //     'email': '',
    // },
]